This is a test case file for 0-add_integer module
=================================================

The "add_integer" function
==========================

Importing module
	>>> add_integer = __import__("0-add_integer").add_integer

Test case: Adding two positive integers
	>>> add_integer(2, 1)
	3

Test case: Adding a positive integer and zero
	>>> add_integer(2, 0)
	2

Test case: Adding zeros
	>>> add_integer(0, 0)
	0

Test case: Adding a positive and negative integer
	>>> add_integer(0, -1)
	-1

Test case: Adding two negative integers
	>>> add_integer(-1, -1)
	-2

Test case: Adding a -ve integer and a charater
	>>> add_integer(-1, a)
	Traceback (most recent call last):
		...
	NameError: name 'a' is not defined

Test case: Adding a character and a positive integer
	>>> add_integer(b, 1)
	Traceback (most recent call last):
		...
	NameError: name 'b' is not defined

Test case: Adding a float and an integer
	>>> add_integer(2.5, 1)
	3

Test case: Adding two floats
	>>> add_integer(2.5, 2.5)
	4

Test case: Adding +ve and -ve floats
	>>> add_integer(2.5, -2.5)
	0

Test case: Adding integer and float
	>>> add_integer(2, 2.5)
	4

Test case: Adding Infinity
	>>> add_integer(float('inf'))
	Traceback (most recent call last):
		...
	OverflowError: cannot convert float infinity to integer

Test case: Adding infinity and an integer
	>>> add_integer(float('inf'), 2)
	Traceback (most recent call last):
		...
	OverflowError: cannot convert float infinity to integer

Test case: Adding integer and infinity
	>>> add_integer(10, float('inf'))
	Traceback (most recent call last):
		...
	OverflowError: cannot convert float infinity to integer

Test case: Adding integer and NaN
	>>> add_integer(10, float('nan'))
	Traceback (most recent call last):
		...
	ValueError: cannot convert float NaN to integer

Test case: Adding two NaN
	>>> add_integer(float('nan'), float('nan'))
	Traceback (most recent call last):
		...
	ValueError: cannot convert float NaN to integer

Test case: Adding a character
	>>> add_integer(a)
	Traceback (most recent call last):
		...
	NameError: name 'a' is not defined

Test case: Calling blank function
	>>> add_integer()
	Traceback (most recent call last):
		...
	TypeError: add_integer() missing 1 required positional argument: 'a'

Test case: Adding two characters
	>>> add_integer("a", "z")
	Traceback (most recent call last):
		...
	TypeError: a must be an integer

Test case: Adding integer and empty list
	>>> add_integer(10, [])
	Traceback (most recent call last):
		...
	TypeError: b must be an integer

Test case: Adding integer and List
	>>> add_integer(10, [3])
	Traceback (most recent call last):
		...
	TypeError: b must be an integer

Test case: Adding integer and tuple
	>>> add_integer(10, (2, 3))
	Traceback (most recent call last):
		...
	TypeError: b must be an integer

Test case: Adding integer to None
	>>> add_integer(10, None)
	Traceback (most recent call last):
		...
	TypeError: b must be an integer

Test case: Adding None
	>>> add_integer(None)
	Traceback (most recent call last):
		...
	TypeError: a must be an integer

Test case: Adding two Nones
	>>> add_integer(None, None)
	Traceback (most recent call last):
		...
	TypeError: a must be an integer

Test case: Adding None and integer
	>>> add_integer(None, 5)
	Traceback (most recent call last):
		...
	TypeError: a must be an integer

Test case: Adding one argument
	>>> add_integer(2)
	100
